"""Pure-JAX compact Dreamer-style world models with Improved MeanFlow priors."""

from .agent import (
    act,
    actor,
    create_agent,
    critic,
    imagine,
    initial_state,
    jit_act,
    jit_imagine,
    jit_train_actor_critic,
    jit_train_world_model,
    lambda_returns,
    train_actor_critic,
    train_world_model,
)
from .checkpoint import CHECKPOINT_VERSION, load_checkpoint, save_checkpoint
from .config import DreamerConfig, PlannerConfig, PriorKind
from .imf import (
    imf_field,
    improved_meanflow_loss,
    init_imf,
    jit_improved_meanflow_loss,
    sample_imf_one_step,
    sample_time_pairs,
)
from .planner import (
    cem_plan,
    evaluate_action_sequences,
    jit_cem_plan,
    jit_evaluate_action_sequences,
)
from .replay import SequenceReplayBuffer
from .types import (
    ActorCriticMetrics,
    AgentParams,
    AgentState,
    DiagonalNormal,
    IMFLossDetails,
    Imagination,
    PlanResult,
    PredictiveMoments,
    RSSMState,
    SequenceStates,
    WorldModelLoss,
)
from .uncertainty import (
    energy_score,
    jit_sample_prior_ensemble,
    predictive_moments,
    sample_prior_ensemble,
    stack_ensemble,
)
from .world_model import (
    decode,
    encode,
    gaussian_kl,
    init_world_model,
    jit_observe_sequence,
    jit_world_model_loss,
    observe_sequence,
    observe_step,
    posterior,
    predict_continuation_logits,
    predict_reward,
    preprocess_observation,
    prior_distribution,
    representation_kl,
    sample_prior,
    transition_deterministic,
    world_model_loss,
)

__version__ = "0.1.0"

__all__ = [
    "CHECKPOINT_VERSION",
    "ActorCriticMetrics",
    "AgentParams",
    "AgentState",
    "DiagonalNormal",
    "DreamerConfig",
    "IMFLossDetails",
    "Imagination",
    "PlanResult",
    "PlannerConfig",
    "PredictiveMoments",
    "PriorKind",
    "RSSMState",
    "SequenceReplayBuffer",
    "SequenceStates",
    "WorldModelLoss",
    "act",
    "actor",
    "cem_plan",
    "create_agent",
    "critic",
    "decode",
    "encode",
    "energy_score",
    "evaluate_action_sequences",
    "gaussian_kl",
    "imagine",
    "imf_field",
    "improved_meanflow_loss",
    "init_imf",
    "init_world_model",
    "initial_state",
    "jit_act",
    "jit_cem_plan",
    "jit_evaluate_action_sequences",
    "jit_imagine",
    "jit_improved_meanflow_loss",
    "jit_observe_sequence",
    "jit_sample_prior_ensemble",
    "jit_train_actor_critic",
    "jit_train_world_model",
    "jit_world_model_loss",
    "lambda_returns",
    "load_checkpoint",
    "observe_sequence",
    "observe_step",
    "posterior",
    "predict_continuation_logits",
    "predict_reward",
    "predictive_moments",
    "preprocess_observation",
    "prior_distribution",
    "representation_kl",
    "sample_imf_one_step",
    "sample_prior",
    "sample_prior_ensemble",
    "sample_time_pairs",
    "save_checkpoint",
    "stack_ensemble",
    "train_actor_critic",
    "train_world_model",
    "transition_deterministic",
    "world_model_loss",
]

